### ISSUE TITLE
`buildah` bottle does not install configuration files

### ISSUE THREAD

**Issue by aeons** [slp/homebrew-krun#7]
I just installed `krunvm`, without having any dependencies already installed.

 Running `krunvm create` fails with the following:
```
loading registries configuration "/opt/homebrew/etc/containers/registries.conf": 
open /opt/homebrew/etc/containers/registries.conf: no such file or directory
buildah returned an error: 
```
If you add that file, it errors with a missing policy file instead.

Running `brew reinstall --build-from-source buildah` fixes the issue.

**Comment by slp** [comment]
Thanks for reporting the issue. Seems like `brew bottle` doesn't include files that already existed when `brew install --build-bottle` was executed. Should be fixed now.
