### ISSUE TITLE
brew install krunvm fail due to v 1.4.8 not found since update to v 1.5.0

### ISSUE THREAD

**Issue by nhat416** [slp/homebrew-krun#9]
> ==> Fetching slp/krun/libkrun
==> Downloading https://raw.githubusercontent.com/slp/homebrew-krun/master/bottles/libkrun-1.4.8.arm64_ventura.bottle.tar.gz
curl: (22) The requested URL returned error: 404                              

> Error: krunvm: Failed to download resource "libkrun"
Download failed: https://raw.githubusercontent.com/slp/homebrew-krun/master/bottles/libkrun-1.4.8.arm64_ventura.bottle.tar.gz

**Comment by slp** [comment]
Oops... I forgot to commit the formula changes. Should be fixed now, please let me know if it doesn't work for you.

**Comment by nhat416** [comment]
Yes works beautifully now thanks @slp and great work with this project.
